"""message

Revision ID: 33a8c6bb18d5
Revises: 10a659300915
Create Date: 2023-10-04 13:26:01.689589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33a8c6bb18d5'
down_revision = '10a659300915'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', sa.String(), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.VARCHAR(),
               type_=sa.LargeBinary(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.LargeBinary(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
        batch_op.drop_column('file_data')

    # ### end Alembic commands ###
