"""image string

Revision ID: 80c94a3ff3a1
Revises: 33a8c6bb18d5
Create Date: 2024-04-22 00:27:30.278394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80c94a3ff3a1'
down_revision = '33a8c6bb18d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('image',
               existing_type=sa.BLOB(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_column('file_data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_data', sa.VARCHAR(), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.String(),
               type_=sa.BLOB(),
               existing_nullable=True)

    # ### end Alembic commands ###
